apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: totcircles-com-tls
spec:
  secretName: totcircles-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: totcircles.com
  dnsNames:
    - totcircles.com
    - www.totcircles.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - totcircles.com
          - www.totcircles.com
